import type { NistControl } from "@/lib/types"

export function loadSampleData(): NistControl[] {
  return [
    {
      control_id: "GV.1.1",
      nist_function: "GV",
      category: "Governance",
      subcategory: "Cybersecurity Risk Management Strategy",
      title: "Establish Cybersecurity Risk Management Strategy",
      description: "Establish and communicate the organization's cybersecurity risk management strategy.",
      priority: "High",
      status: "In Progress",
      compliance_level: 50,
      implementation_notes: "Strategy document in draft form, pending executive review.",
    },
    {
      control_id: "ID.1.1",
      nist_function: "ID",
      category: "Asset Management",
      subcategory: "Asset Inventory",
      title: "Inventory Physical Devices",
      description: "Physical devices and systems within the organization are inventoried.",
      priority: "High",
      status: "Completed",
      compliance_level: 100,
      implementation_notes: "Asset inventory system implemented and regularly updated.",
    },
    {
      control_id: "PR.2.1",
      nist_function: "PR",
      category: "Identity Management & Access Control",
      subcategory: "Authentication & Authorization",
      title: "Manage Identities and Credentials",
      description:
        "Identities and credentials are issued, managed, verified, revoked, and audited for authorized devices, users, and processes.",
      priority: "High",
      status: "In Progress",
      compliance_level: 75,
      implementation_notes: "SSO implementation in progress, 75% complete.",
    },
    {
      control_id: "DE.1.2",
      nist_function: "DE",
      category: "Anomalies and Events",
      subcategory: "Event Detection",
      title: "Detect Malicious Code",
      description: "Malicious code is detected.",
      priority: "Medium",
      status: "Not Started",
      compliance_level: 0,
      implementation_notes: "Evaluating EDR solutions.",
    },
    {
      control_id: "RS.1.1",
      nist_function: "RS",
      category: "Response Planning",
      subcategory: "Response Plan",
      title: "Execute Response Plan",
      description: "Response plan is executed during or after an incident.",
      priority: "Medium",
      status: "In Progress",
      compliance_level: 30,
      implementation_notes: "Incident response plan drafted, tabletop exercises scheduled.",
    },
    {
      control_id: "RC.1.1",
      nist_function: "RC",
      category: "Recovery Planning",
      subcategory: "Recovery Plan",
      title: "Execute Recovery Plan",
      description: "Recovery plan is executed during or after a cybersecurity incident.",
      priority: "Medium",
      status: "Not Started",
      compliance_level: 0,
      implementation_notes: "Recovery planning to begin next quarter.",
    },
  ]
}
